# Numpy

In [1]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
a = np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [ ]:
a = np.ones(100) * 3
a

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
np.info(np.add)

#### 5. Поменять 2 строки в матрице

In [ ]:
a = np.random.rand(5, 5)
print(a)
i = 1
j = 2
tmp = np.copy(a[i, :])
a[i, :] = a[j, :]
a[j, :] = tmp
print(a)

[[0.73844354 0.27918736 0.88326518 0.02203731 0.27293284]
 [0.90232536 0.09628963 0.82802931 0.68777783 0.47161682]
 [0.14887869 0.06724058 0.11097396 0.56348753 0.92404532]
 [0.6277445  0.85834883 0.97496186 0.32215574 0.87431303]
 [0.48887585 0.79643636 0.78283702 0.86031321 0.29348326]]
[[0.73844354 0.27918736 0.88326518 0.02203731 0.27293284]
 [0.14887869 0.06724058 0.11097396 0.56348753 0.92404532]
 [0.90232536 0.09628963 0.82802931 0.68777783 0.47161682]
 [0.6277445  0.85834883 0.97496186 0.32215574 0.87431303]
 [0.48887585 0.79643636 0.78283702 0.86031321 0.29348326]]


#### 6. Создать вектор со значениями от 10 до 100

In [ ]:
a = np.arange(10, 101, 1)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [ ]:
a = np.arange(10, 101, 1)
a = a[::-1]
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
a = np.linspace((np.arange(4)),(np.arange(13,17)), 4)
a

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.33333333,  5.33333333,  6.33333333,  7.33333333],
       [ 8.66666667,  9.66666667, 10.66666667, 11.66666667],
       [13.        , 14.        , 15.        , 16.        ]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a = np.insert(a, np.arange(0, len(a)), 0)
a = np.insert(a, np.arange(1, len(a), 2), 0)
a = np.insert(a, np.arange(1, len(a), 3), 0)
a

array([0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 10. Создать 3x3 единичную матрицу

In [ ]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [ ]:
a = np.random.rand(3, 3, 3)
a

array([[[0.61717674, 0.41375355, 0.33865688],
        [0.78888176, 0.89995659, 0.69416681],
        [0.52069069, 0.68856555, 0.78653872]],

       [[0.21643456, 0.82852789, 0.34095533],
        [0.02949457, 0.04841013, 0.61079531],
        [0.02581626, 0.85227919, 0.417706  ]],

       [[0.42998655, 0.46162635, 0.68724255],
        [0.89672432, 0.93829914, 0.08681014],
        [0.47842605, 0.9157628 , 0.99831441]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
a = np.random.rand(10, 10)
print(np.max(a))
print(np.min(a))

0.9889322687294598
0.002332653110685645


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
a = np.random.rand(30)
print(np.mean(a))

0.42346888022236956


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
a = np.ones((5, 5))
a[1:-1:, 1:-1:] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [5]:
a = np.random.randint(0, 5, (5, 5, 5))
print(a)
np.rot90(a, axes=(0, 1))

[[[1 2 4 2 1]
  [0 3 1 2 2]
  [0 2 0 2 0]
  [0 4 1 1 2]
  [3 0 2 0 0]]

 [[3 1 4 2 4]
  [0 1 4 1 0]
  [3 1 2 2 1]
  [4 3 2 2 1]
  [3 2 2 2 2]]

 [[3 4 4 2 1]
  [1 1 0 3 3]
  [1 1 3 0 0]
  [0 3 2 4 2]
  [2 2 0 4 3]]

 [[3 2 4 2 1]
  [3 2 4 4 3]
  [1 0 3 1 0]
  [4 1 4 0 1]
  [1 2 3 2 2]]

 [[2 0 1 1 0]
  [2 4 4 4 3]
  [0 1 4 1 2]
  [2 1 4 3 3]
  [0 3 4 4 3]]]


array([[[3, 0, 2, 0, 0],
        [3, 2, 2, 2, 2],
        [2, 2, 0, 4, 3],
        [1, 2, 3, 2, 2],
        [0, 3, 4, 4, 3]],

       [[0, 4, 1, 1, 2],
        [4, 3, 2, 2, 1],
        [0, 3, 2, 4, 2],
        [4, 1, 4, 0, 1],
        [2, 1, 4, 3, 3]],

       [[0, 2, 0, 2, 0],
        [3, 1, 2, 2, 1],
        [1, 1, 3, 0, 0],
        [1, 0, 3, 1, 0],
        [0, 1, 4, 1, 2]],

       [[0, 3, 1, 2, 2],
        [0, 1, 4, 1, 0],
        [1, 1, 0, 3, 3],
        [3, 2, 4, 4, 3],
        [2, 4, 4, 4, 3]],

       [[1, 2, 4, 2, 1],
        [3, 1, 4, 2, 4],
        [3, 4, 4, 2, 1],
        [3, 2, 4, 2, 1],
        [2, 0, 1, 1, 0]]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [ ]:
a = np.diag([1, 2, 2, 4], k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
a = np.zeros((5, 5))
a[0::2, 0::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
a = np.random.randint(-100, 100, (6, 7, 8))
i = 100 // (7 * 8)
j = 100 % (7 * 8) // 8
k = 100 % (7 * 8) % 8
print(a[i, j, k])
a = a.reshape(a.size)
print(a[100])

48
48


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [ ]:
a = np.random.randint(0, 10, (5, 3))
b = np.random.randint(0, 10, (3, 2))
print(a.dot(b))
print(a @ b)

[[ 89 104]
 [ 46  60]
 [ 57  52]
 [ 71  64]
 [ 67  84]]
[[ 89 104]
 [ 46  60]
 [ 57  52]
 [ 71  64]
 [ 67  84]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
a = np.random.randint(0, 10, 20)
print(a)
a[(a > 3) & (a < 8)] = a[(a > 3) & (a < 8)] * (-1)
a

[2 1 4 1 7 3 9 4 8 3 6 3 4 9 0 3 5 7 8 0]


array([ 2,  1, -4,  1, -7,  3,  9, -4,  8,  3, -6,  3, -4,  9,  0,  3, -5,
       -7,  8,  0])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
a = np.random.randint(0, 5, (5, 5))
a

array([[3, 4, 1, 3, 0],
       [3, 4, 2, 4, 0],
       [0, 2, 0, 1, 4],
       [2, 4, 2, 2, 0],
       [3, 2, 0, 4, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [ ]:
iter = (x for x in range(5))
a = np.fromiter(iter, int)
a

array([0, 1, 2, 3, 4])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
a = np.linspace(0, 1, 11, endpoint=0)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [ ]:
a = np.random.randint(0, 10, 20)
print(a)
a.sort()
print(a)

[2 4 9 7 2 8 4 7 5 0 1 7 1 9 7 3 5 6 4 0]
[0 0 1 1 2 2 3 4 4 4 5 5 6 7 7 7 7 8 9 9]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [ ]:
a = np.arange(10)
b = np.arange(10)
np.array_equal(a, b)

True

#### 28. Сделать массив неизменяемым

In [ ]:
a = np.arange(10)
a.flags.writeable = False
# a[0] = 1 - выдаст ошибку

#### 29. Найти n наибольших значений в массиве

In [ ]:
a = np.random.randint(-100, 100, 20)
a.sort()
print(a)
n = 5
a[-n::1]

[-98 -95 -74 -57 -35 -28 -19 -17 -10  -1  21  22  49  55  57  65  67  67
  82  93]


array([65, 67, 67, 82, 93])

#### 30. Заменить максимальный элемент на ноль

In [ ]:
a = np.random.randint(-100, 100, 20)
print(a)
print('index', np.argmax(a))
a[np.argmax(a)] = 0
print(a)

[-47 -20 -18  54  50   8   0  57  43 -63 -67  66 -29  24  18 -53 -36   6
 -24 -13]
index 11
[-47 -20 -18  54  50   8   0  57  43 -63 -67   0 -29  24  18 -53 -36   6
 -24 -13]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))

[array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.1111

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
x = np.arange(5)
y = np.arange(4)
x = x.reshape((-1,1))
diff = x - y
C = 1 / diff
C

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([[        inf, -1.        , -0.5       , -0.33333333],
       [ 1.        ,         inf, -1.        , -0.5       ],
       [ 0.5       ,  1.        ,         inf, -1.        ],
       [ 0.33333333,  0.5       ,  1.        ,         inf],
       [ 0.25      ,  0.33333333,  0.5       ,  1.        ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [7]:
print(np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print(np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print(np.finfo(np.float32).min, np.finfo(np.float32).max)
print(np.finfo(np.float64).min, np.finfo(np.float64).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.random.rand(25, 25))

[[0.10348716 0.94264634 0.85010633 0.75457925 0.63566026 0.75671741
  0.36307675 0.36615833 0.42633671 0.20936594 0.43300559 0.1825456
  0.69786618 0.97806309 0.22435127 0.9606852  0.9241653  0.24603347
  0.09690387 0.33621502 0.77014129 0.82146048 0.3903655  0.95264862
  0.74626603]
 [0.24283012 0.75841871 0.73620236 0.61576115 0.8713227  0.87873655
  0.94114213 0.14697696 0.8236334  0.37524632 0.99231953 0.4334992
  0.60072989 0.5435454  0.60493497 0.82840906 0.80697363 0.73041062
  0.61493149 0.7621387  0.58310695 0.14946    0.80315757 0.79148685
  0.45620656]
 [0.91159302 0.00160796 0.8813326  0.04355665 0.23352495 0.02209351
  0.24874402 0.31691804 0.4715811  0.15144556 0.7114944  0.64941175
  0.71791125 0.19167016 0.29833414 0.18836643 0.95466204 0.97029883
  0.04742921 0.46069509 0.14394884 0.65606989 0.87375674 0.1363872
  0.30191731]
 [0.08267866 0.00397282 0.42783533 0.95794474 0.45790732 0.08251001
  0.50910836 0.45577031 0.52819859 0.79499799 0.84496158 0.56236561
  0.88105

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
a = np.random.rand(20)
number = 0.5
print(a)
a = a - number
print(np.min(abs(a)) + number)

[0.71641493 0.89331926 0.34059551 0.61973343 0.9717906  0.78686907
 0.37053233 0.94967526 0.98022395 0.85864693 0.27085002 0.29324811
 0.55294684 0.4931733  0.15493984 0.75972747 0.32095175 0.68482578
 0.03385714 0.98977053]
0.5068266996895782


#### 36. Преобразовать массив из float в int

In [ ]:
a = np.array([1, 2, 2.5, 3, 3.5])
a = a.astype(int)
a

array([1, 2, 2, 3, 3])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)
# answer is np.ndenumerate

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 38. Случайно расположить p элементов в 2D массив

In [ ]:
a = np.zeros((5, 5))
a = np.reshape(a, -1)
p = np.array([1, 2, 3, 4, 5])
p_ind = np.random.choice(range(25), len(p), replace=False)
a[p_ind] = p
a = np.reshape(a, (5, 5))
a

array([[0., 1., 0., 0., 0.],
       [0., 5., 0., 3., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 2., 4., 0.],
       [0., 0., 0., 0., 0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
a = np.random.randint(1, 20, (5, 5))
a = a - a.mean(axis=1, keepdims=True)
a

array([[ 2.4,  4.4, -0.6, -8.6,  2.4],
       [-4.6, -0.6,  8.4, -1.6, -1.6],
       [ 1.6,  3.6, -2.4,  3.6, -6.4],
       [ 2. , -9. ,  7. ,  3. , -3. ],
       [-0.6, -4.6,  3.4,  1.4,  0.4]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
n = 2 # column n-1
a = np.random.randint(1, 20, (5, 5))
ind = np.argsort(a[:,n])
a = a[ind]
a

array([[16,  6,  5,  9,  5],
       [ 6,  6,  5,  7, 16],
       [15,  3,  7,  3,  2],
       [ 5,  5,  8,  1, 18],
       [16,  5, 17,  1,  7]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
a = np.random.randint(0, 2, (3, 15))
print(a)
b = np.any(a, axis=0)
np.where(b == False)

[[0 0 1 1 1 0 1 0 1 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 1 1 1 1 1 0 0 1]
 [1 1 1 0 1 1 1 1 1 0 0 0 0 0 0]]


(array([12, 13]),)

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
a = np.random.randint(0, 20, 15)
print(a)
b = np.random.randint(0, len(a), 5)
print(b)
a[np.unique(b)] = a[np.unique(b)] + 1
print(a)

[16 17  8  9 14  9  8 19 15 10 19  6 16 19  0]
[ 1  1  4  8 12]
[16 18  8  9 15  9  8 19 16 10 19  6 17 19  0]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [17]:
w = 16
h = 16
I = np.random.randint(0, 2, (w,h,3)).astype(np.ubyte)
F = I[:, :, 0] * 256 * 256 + I[:, :, 1] * 256 + I[:, :, 2]
n = len(np.unique(F))
n

4

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
a = np.random.randint(0,10, (3,3,3,3))
a = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
a

array([[32, 48, 47],
       [45, 42, 38],
       [42, 52, 39]])